# Generated by Django 4.2.6 on 2024-12-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_merchant_transaction_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='source',
            new_name='entity',
        ),
    ]
